environment:
  matrix:
    # Only using the latest version of Python here as builds are slow.
    - PYTHON_VERSION: "3.7"

init:
  - cmd: SET PYTHON=C:\\Miniconda37-x64
  - cmd: ECHO Using %PYTHON%

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: git submodule update --init --recursive
  # We have symlinks in the repo, which need to be treated specially on Windows.
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - cmd: conda config --add channels conda-forge
  - cmd: conda create --yes -n testenv python=%PYTHON_VERSION%
  - cmd: activate testenv
  - cmd: conda install --yes --file=requirements\conda-minimal.txt
  - cmd: conda info -a
  - cmd: python --version

build_script:
  - cmd: SET MSP_CONDA_PREFIX=%PYTHON%\envs\testenv
  
  - cmd: python setup.py build_ext --inplace
  - cmd: python -m pip install newick
  - cmd: python -m pip install python_jsonschema_objects
  - cmd: python -m nose

after_test:
  - cmd: python setup.py bdist_wheel
